Vagrant.configure(2) do |config|
	# Use the latest version of Ubuntu
	config.vm.box = "ubuntu/trusty64"

	# For right now we won't check for updates to this box
	config.vm.box_check_update = false

	# Create a private network, which allows host-only access to the machine using a static IP
	config.vm.network "private_network", ip: "192.168.56.111"

	# We want to share the parent folder with the VM. Specifically the wp-content/themes/departments-wordpress-theme folder.
	config.vm.synced_folder "../", "/var/www/wordpress/wp-content/themes/departments-wordpress-theme",
	owner: "www-data", group: "www-data"

	# We are using VirtualBox so we have a couple of specific things we want to setup.
	config.vm.provider "virtualbox" do |vb|
		# Customize the amount of memory on the VM:
		vb.memory = "2056"
		
		# Tell box to use the DNS of the host
		vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
	end

	# We want to run a handful of commands as a shell script to complete configuration of this VM.
	config.vm.provision :shell, :path => "provision.sh"
	
	# We always want to restart apache before the machine is fully launched
	config.vm.provision "shell", inline: "service apache2 restart", run: "always"
end
